version: '3.4'

services:
  igscrudapi:
    image: igscrudapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123+
    ports:
      - "14331:1433"  
