version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123+
    ports:
      - "14331:1433"
    healthcheck:
          test: /opt/mssql-tools/bin/sqlcmd -S db -U sa -P "Password123+" -Q "SELECT 1" || exit 1
          interval: 10s
          timeout: 3s
          retries: 10
          start_period: 10s
  igscrudapi:
    image: igscrudapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
  
